spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  datasource:
    druid:
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
      driver-class-name: ${sky.datasource.driver-class-name}


  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl







#knife4j配置
# Knife4j配置
# springdoc-openapi配置
